version: "3"
services:
  node:
    image: alexdv/task6:node
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=8080
    networks:
      - net
    volumes:
      - ./src:/user/app/src/
  postgres:
    image: alexdv/task6:db
    restart: always
    networks:
      - net
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=password

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24
#
#version: '3'
#
#services:
#  express:
#    restart: always
#    build: .
#    image: yuskivpm/rss-2021q2-nodejs:express_v1.0
#    ports:
#      - ${HOST_PORT}:${CONTAINER_PORT}
#    depends_on:
#      - ${DB_TYPE}
#    env_file:
#      - .env
#    volumes:
#      - ./src:/usr/express/app/src
#      - /usr/express/app/node_modules/
#      - ${LOG_FOLDER}:/usr/express/app/logs
#    networks:
#      users:
#
#  postgres:
#    container_name: ${DB_HOST}
#    restart: always
#    build: ./database/
#    image: yuskivpm/rss-2021q2-nodejs:postgres_v1.0
#    ports:
#      - ${DB_PORT}:${DB_PORT}
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    volumes:
#      - ${DB_PATH}:${PGDATA}
#    networks:
#      users:
#        aliases:
#          - postgres
#
#networks:
#  users:
#    driver: bridge
